#!/usr/bin/env ansible-playbook
#
# Examples to call:
#    ansible-navigator run ./labvms.yml -i inventory.ini --vault-id "vault_password.sh" --limit ansvm[1-2].lab.linder.org
# Or
#   ansible-navigator run labvms.yml -i inventory.ini --limit anssrv.lab.linder.org, --user dan --private-key ~/.ssh/id_ed25519
#
# May need to refresh the Collections and Roles:
#   ansible-galaxy collection install -r collections/requirements -p ./collections
#
# On each VM power them up, connect to the .25 address then run these:
# NUM=3
# nmcli con mod ens33 ipv4.address 192.168.65.2${NUM}/24 && hostnamectl set-hostname ansvm${NUM} && reboot
#
---
- name: "Do things on all systems"
  hosts: all
  gather_facts: true

  vars:
    rh_sub_info:
      name: 'dan-5'
      # ansible-vault encrypt_string --name password 'MyPa$$wordH3re!'
      password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66303435316366383830366338343639373930356330383665366265353430343332666436376336
          3236636666623131363365316164336233363735636361370a643963663736373364323137363033
          34353738386531323338386165383530333063656637663634643766663361313066393366653637
          3131636537323863650a336133643836623336643135633262303261643338336536386438373064
          61643833303339623432653534383465656563663235316533313766303437393539

    ssh_users:
    - name: 'dan'
      key: 'id_ed25519.pub'
 
    common_packages:
      - "vim"
      - "yum-utils"

  tasks:
  - name: 'Setup .ssh folder'
    file:
      path: '/home/{{ ansible_ssh_user }}/.ssh' #'{{ lookup("env","HOME") + "/.ssh/" }}'
      state: directory
      mode: 0700

  - name: 'Setup SSH key on remote systems so local $USER can SSH in without password'
    ansible.posix.authorized_key:
      user: '{{ item.name }}'
      key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/" + item.key ) }}'
      state: present
    loop: '{{ ssh_users }}'

  - name: "Set hostname"
    ansible.builtin.hostname:
      name: '{{ inventory_hostname }}'
    become: true
    
  - name: 'Adjust so $USER on remote system can "sudo" without password'
    lineinfile:
      path: '/etc/sudoers.d/{{ item.name }}'
      state: present
      line:  '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
      create: True
      mode: 0640
      owner: root
      group: root
      validate: '/usr/sbin/visudo -cf %s'
    become: true
    #become_method: su
    loop: '{{ ssh_users }}'

  - name: "Ensure Red Hat Subscription setup"
    community.general.redhat_subscription:
      state: present
      username: '{{ rh_sub_info.name }}'
      password: '{{ rh_sub_info.password }}'
      syspurpose:
        usage: "Development/Test"
        role: "Red Hat Enterprise Linux Server"
        service_level_agreement: "Self-Support"
        sync: yes
      auto_attach: true
    become: true

  - name: 'Add some handy common packages'
    package:
      name: '{{ common_packages }}'
      state: installed
    become: true

  - name: 'Patch up the systems'
    package:
      name: '*'
      state: latest
    notify: reboot
    become: true

  handlers:
  - name: reboot
    reboot:
      msg: "Reboot initiated by Ansible" # not required. Message to display to users before reboot.
    become: true
    when:
    -  not ansible_env['SSH_CLIENT'] | regex_search(ansible_facts.all_ipv4_addresses[0])
    -  not ansible_env['SSH_CLIENT'] | regex_search(ansible_facts.all_ipv4_addresses[1] | default(ansible_facts.all_ipv4_addresses[0]))
    -  not ansible_env['SSH_CLIENT'] | regex_search(ansible_facts.all_ipv4_addresses[2] | default(ansible_facts.all_ipv4_addresses[0]))
    -  not ansible_env['SSH_CLIENT'] | regex_search(ansible_facts.all_ipv4_addresses[3] | default(ansible_facts.all_ipv4_addresses[0]))


