#!/usr/bin/env bash
set -u
set -e
#set -x

# This will build the base VMs used for the "k32-ansible"
# playbook: https://github.com/k3s-io/k3s-ansible.git

# How long to delay before rescanning for inventory
DEL=5

set +e
TFBIN=$(which terraform 2>/dev/null)
set -e
if [[ "${TFBIN}" == "" ]] ; then
  echo "Can't find terraform binary. Exiting."
  exit 1
fi

set +e
OVFBIN=$(which ovftool 2>/dev/null)
set -e
if [[ "${OVFBIN}" == "" ]] ; then
  echo "Can't find ovftool binary. Exiting."
  exit 1
fi

echo "Starting: $(date)"
terraform init
terraform plan
terraform destroy -auto-approve

figlet 'READY!'

echo "Starting build: $(date)"
time terraform apply -auto-approve
echo "Inventory right after terraform apply:"
cat -n inventory
sleep ${DEL}
time terraform apply -auto-approve
echo "Inventory after ${DEL} second delay:"
cat -n inventory

figlet 'Done.'

echo "Starting setup: $(date)"
time ansible-playbook -i inventory ./setupokd4.yml -u root
#time ansible-playbook -i inventory ~/SetupHomeLab/main.yml -u root
echo "Completed setup: $(date)"

