#!/usr/bin/ansible-playbook
---
- hosts: all
  gather_facts: true

  tasks:
  - name: Setup passwordless sudo
    become: true
    lineinfile:
      path: /etc/sudoers
      state: present
      line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
      validate: /usr/sbin/visudo -cf %s

  - name: Setup hostname
    include_role:
      name: fqdn
      apply:
        become: true
    vars:
      fqdn: "{{ inventory_hostname }}"
      hostname: "{{ inventory_hostname_short }}"
#
- hosts: services
  gather_facts: true

  tasks:
  - name: Setup automatic updates
    become: true
    package:
      state: installed
      name:
      - dnf-automatic
    when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version|int >= 8

  - name: "Install EPEL"
    become: true
    package:
      state: installed
      name:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    register: install_epel
    when:
      - ansible_distribution in [ 'RedHat', 'CentOS' ]
      - ansible_os_family == 'RedHat'

  - name: "Ensure RedHat 8 has the repositores setup"
    become: true
    rhsm_repository:
      name:
        - "ansible-2-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms" # Red Hat Ansible Engine 2 for RHEL 8 x86_64
      state: enabled
    when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution == 'RedHat'
      - ansible_distribution_major_version|int == 8
    register: install_repos

  - name: "Ensure RedHat 7 has the repositores setup"
    become: true
    rhsm_repository:
      name:
        - "rhel-{{ ansible_distribution_major_version }}-server-extras-rpms"
        - "rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
        - "rhel-{{ ansible_distribution_major_version }}-server-ansible-2.9-rpms"
      state: enabled
    when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution == 'RedHat'
      - ansible_distribution_major_version|int == 7
    register: install_repos

  - name: Update repository cache
    become: true
    package:
      update_cache: yes
      state: latest
      name: "*"
    notify: do_reboot

  - name: Install Chrome browser
    become: true
    package:
      name: chromium

  - name: Install XRDP
    become: true
    package:
      name:
        - xrdp
        - tigervnc-server

  - name: Enable XRDP
    service:
      name: xrxp
      state: started
      enabled: true
    notify: restart_firewalld

  - name: Open up XRDP FW port
    firewalld:
      service: xrxp
      permanent: true
      state: enabled
    notify: restart_firewalld

  # Setup local DNS server
  - name: Install bind apps
    become: true
    package:
      name:
        - bind
        - bind-utils

  - name: Build named.conf file
    template:
      src: templates/named.conf.j2
      dest: /etc/named.conf
      setype: named_conf_t
      seuser: system_u
      serole: object_r
      mode: 0640
      group: named

  - name: Build named.conf.local file
    template:
      src: templates/named.conf.local.j2
      dest: /etc/named/named.conf.local
      setype: named_conf_t
      seuser: system_u
      serole: object_r
      mode: 0640
      group: named

  - name: Build db.okd.local file
    template:
      src: templates/db.okd.local.j2
      dest: /etc/named/db.okd.local
      setype: named_conf_t
      seuser: system_u
      serole: object_r
      mode: 0640
      group: named

  - name: Build db.subnet file
    template:
      src: templates/db.subnet.j2
      dest: /etc/named/db.subnet
      setype: named_conf_t
      seuser: system_u
      serole: object_r
      mode: 0640
      group: named

  - name: Enable named
    service:
      name: named
      state: started
      enabled: true
    notify: restart_firewalld

  - name: Open up named FW port
    firewalld:
      port: 53/udp
      permanent: true
      state: enabled
    notify: restart_firewalld

  # Setup local HAProxy

  - name: Install HAproxy
    become: true
    package:
      name:
        - haproxy

  - name: Build haproxy.cfg
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      # setype: named_conf_t
      # seuser: system_u
      # serole: object_r
      mode: 0644
      # group: named

  - name: Set SELinux haproxy boolean values
    seboolean:
      name: haproxy_connect_any
      state: yes
      persistent: yes

  - name: Enable haproxy
    service:
      name: haproxy
      state: started
      enabled: true

  - name: Open up OKD4 FW ports
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - 6443/tcp
      - 22623/tcp
    notify: restart_firewalld

  - name: Open up OKD4 FW services
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - http
      - https
    notify: restart_firewalld
#
  # Setup local HAProxy
  - name: Install Apache
    become: true
    package:
      name:
        - httpd

  - name: Setup Apache to listen on 8080
    become: true
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: 'Listen 8080'

  - name: Set SELinux Apache boolean values
    seboolean:
      name: httpd_read_user_content 
      state: yes
      persistent: yes

  - name: Enable httpd
    service:
      name: httpd
      state: started
      enabled: true

  - name: Open up OKD4 FW ports
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items:
      - 8080/tcp
    notify: restart_firewalld

  - name: Update NetworkManager.conf
    ini_file:
      dest: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none
      backup: yes
      owner: root
      group: root
      mode: 0644
    register: netmgr
    when: ansible_distribution_major_version|int >= 7

  - name: Ensure dns servers are configured in /etc/resolv.conf
    template:
      src: templates/resolv.conf.j2
      dest: /etc/resolv.conf
      backup: yes
      owner: root
      group: root
      mode: 0644
      
  - name: Restart NetworkManger
    service:
      name: NetworkManager
      state: restarted
      enabled: yes
    when: netmgr is changed

  handlers:
  - name: restart_firewalld
    become: true
    systemd:
      name: firewalld
      state: reloaded

  - name: do_reboot
    become: true
    reboot:
#
- hosts: pfsense
  gather_facts: true

  # Include this module?
  # https://github.com/opoplawski/ansible-pfsense/

  tasks:
  - name: Do stuff
    debug:
      msg: "Do stuff here"

#
- hosts: bootstrap
  gather_facts: true

  tasks:
  - name: Do stuff
    debug:
      msg: "Do stuff here"

  handlers:
  - name: do_reboot
    become: true
    reboot:

#
- hosts: control_plane
  gather_facts: true
  
  tasks:
  - name: Do stuff
    debug:
      msg: "Do stuff here"

  handlers:
  - name: do_reboot
    become: true
    reboot:
#
- hosts: compute
  gather_facts: true
  
  tasks:
  - name: Do stuff
    debug:
      msg: "Do stuff here"

  handlers:
  - name: do_reboot
    become: true
    reboot:
#
