root_passwd: "Today123!"
vcenter_hostname: "esx.lab.linder.org"
esxi_hostname: "{{ vcenter_hostname }}"
vcenter_username: "root"
vcenter_password: "1234NewS!@#$"
initial_sshkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKDnvLrwffOBQ6FYCu8NpJ/rDwIfsQSVVHvf3Dk5dqud dan@anssrv"

vminfo:
- name: "okd4-services"
  guest_id: "rhel8_64Guest"
  in_group: [ "services", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "services.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "VM Network"
    mac: "00:50:56:01:00:10"
    address: "192.168.65.140"
    netmask: "255.255.255.0"
  - nicname: "OKD"
    mac: "00:50:56:01:01:10"
    address: "192.168.1.210"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 4096
  HDD:
    size: 100
    datastore: "datastore1"

- name: "okd4-pfsense"
  guest_id: "rhel8_64Guest"
  in_group: [ "pfsense", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "pfsense.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "VM Network"
    mac: "00:50:56:01:00:11"
    address: "192.168.65.141"
    netmask: "255.255.255.0"
  - nicname: "OKD"
    mac: "00:50:56:01:01:11"
    address: "192.168.1.1"
    netmask: "255.255.255.0"
  CPUs: 1
  RAM: 1024
  HDD:
    size: 8
    datastore: "datastore1"

- name: "okd4-bootstrap"
  guest_id: "rhel8_64Guest"
  in_group: [ "bootstrap", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "bootstrap.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "OKD"
    mac: "00:50:56:01:01:12"
    address: "192.168.1.200"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 16384
  HDD:
    size: 120
    datastore: "datastore1"

- name: "okd4-control-plane-1"
  guest_id: "rhel8_64Guest"
  in_group: [ "control-plane", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "control-plane.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "OKD"
    mac: "00:50:56:01:01:13"
    address: "192.168.1.201"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 16384
  HDD:
    size: 120
    datastore: "datastore1"

- name: "okd4-control-plane-2"
  guest_id: "rhel8_64Guest"
  in_group: [ "control-plane", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "control-plane.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "OKD"
    mac: "00:50:56:01:01:14"
    address: "192.168.1.202"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 16384
  HDD:
    size: 120
    datastore: "datastore1"

- name: "okd4-control-plane-3"
  guest_id: "rhel8_64Guest"
  in_group: [ "control-plane", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "control-plane.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "OKD"
    mac: "00:50:56:01:01:15"
    address: "192.168.1.203"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 16384
  HDD:
    size: 120
    datastore: "datastore1"

- name: "okd4-compute-1"
  guest_id: "rhel8_64Guest"
  in_group: [ "compute", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "compute.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "OKD"
    mac: "00:50:56:01:01:16"
    address: "192.168.1.204"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 16384
  HDD:
    size: 120
    datastore: "datastore1"

- name: "okd4-compute-2"
  guest_id: "rhel8_64Guest"
  in_group: [ "compute", "newvms" ]
  kickstart_template: "services.ks.j2"
  kickstart_file: "compute.ks"
  iso: "[datastore1] isos/CentOS-8.2.2004-x86_64-dvd1.iso"
  iso_label: "CentOS-8-2-2004-x86_64-dvd"
  boot_string: "vmlinuz initrd=initrd.img inst.stage2=hd:LABEL=CentOS-8-2-2004-x86_64-dvd inst.ks=http://_HTTPD_IP_:_HTTPD_PORT_/_KS_FILE_"
  defgw: "192.168.65.1"
  dns: "192.168.65.7"
  nics:
  - nicname: "OKD"
    mac: "00:50:56:01:01:17"
    address: "192.168.1.205"
    netmask: "255.255.255.0"
  CPUs: 4
  RAM: 16384
  HDD:
    size: 120
    datastore: "datastore1"
